### PR TITLE
fixed error

### PR DESCRIPTION
**Pull request by DominikGuentensperger**
hello

### CODE REVIEW

**Review by ArnaudKunzi — CHANGES_REQUESTED** [review]
is that it?
I would have preferred  that you remove the line instead of just commenting-it out. Version control is there in case we need to recover old code.

**Comment by DominikGuentensperger** [comment]
ok

**Comment by ArnaudKunzi** [comment]
don't forget to fix the checks too! (ASAP...)

**Comment by DominikGuentensperger** [comment]
yeah yeah

**Comment by ArnaudKunzi** [comment]
Sounds good! Good work!

**Pull request merged**
